package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/llbbl/dotfiles-manager/internal/config"
	"github.com/spf13/cobra"
)

// Fragment filenames, one per syntax family. zsh reads the POSIX file
// rather than getting its own: fish cannot source POSIX syntax, but sh,
// bash and zsh all can, so two files cover every shell.
const (
	pathFragmentPosixName = "env.sh"
	pathFragmentFishName  = "env.fish"
)

// pathFragmentName maps a rendering family to its fragment filename.
func pathFragmentName(family string) string {
	if family == "fish" {
		return pathFragmentFishName
	}
	return pathFragmentPosixName
}

// renderPathFragment re-renders managed rc-file entries as a standalone
// sourceable file: a generated-file header, then the marker-delimited
// blocks unchanged. Prepend entries come first so the final PATH order
// matches what the rc file produced.
func renderPathFragment(family string, entries []PathManagedEntry) string {
	var b strings.Builder
	// The warning stays generic on purpose: before a migrate dfm
	// regenerates this whole file, after one it only rewrites the blocks.
	fmt.Fprintf(&b, "# Generated by dfm. Manage entries with 'dfm path add' and 'dfm path remove'.\n")
	fmt.Fprintf(&b, "# Canonical location: %s\n", config.FragmentPath(pathFragmentName(family)))

	// Anything that is not append is prepend, matching pathListRows. A
	// hand-edited direction= token would otherwise be listed but never
	// rendered, and the re-render keeps the original token either way.
	for _, wantAppend := range []bool{false, true} {
		for _, e := range entries {
			if (e.Marker.Direction == pathDirectionAppend) != wantAppend {
				continue
			}
			b.WriteString(renderPathBlock(family, e.Marker.ID, e.Marker.UpdatedAt,
				e.Marker.Direction, e.Marker.Dirs))
		}
	}
	return b.String()
}

// newPathFragmentCmd prints the fragment that would be installed at
// config.FragmentPath. Read-only: nothing is written here, and an rc
// file with no managed blocks yields the header alone.
func newPathFragmentCmd() *cobra.Command {
	var (
		shellFlag string
		fileFlag  string
		fishFlag  bool
	)
	cmd := &cobra.Command{
		Use:   "fragment",
		Short: "Print the generated PATH fragment for the target rc file",
		Args:  cobra.NoArgs,
		RunE: func(c *cobra.Command, _ []string) error {
			if shellFlag != "" && fileFlag != "" {
				return exitf(exitResolveErr,
					"path fragment: --shell and --file are mutually exclusive")
			}

			target, targetFamily, err := resolvePathTarget(c.Context(), shellFlag, fileFlag)
			if err != nil {
				return err
			}

			data, err := os.ReadFile(target)
			if err != nil && !os.IsNotExist(err) {
				return fmt.Errorf("read %s: %w", target, err)
			}

			// Which rc file the entries are read from and which syntax
			// they are rendered in are separate choices. The target's own
			// family is the sane default; --fish asks for the other
			// fragment from the same entries. zsh resolves to posix
			// because env.sh is the file zsh ends up sourcing.
			family := "posix"
			if fishFlag || targetFamily == "fish" {
				family = "fish"
			}
			_, err = fmt.Fprint(c.OutOrStdout(),
				renderPathFragment(family, findPathManagedEntries(data)))
			return err
		},
	}
	cmd.Flags().StringVar(&shellFlag, "shell", "", "shell to target (bash|zsh|fish|profile)")
	cmd.Flags().StringVar(&fileFlag, "file", "", "explicit rc file (mutually exclusive with --shell)")
	cmd.Flags().BoolVar(&fishFlag, "fish", false, "render the fish fragment instead of the POSIX one")
	return cmd
}
