package main

import (
	"bytes"
	"context"
	"errors"
	"strings"
	"testing"
)

func runPathFragmentCmd(t *testing.T, ctx context.Context, args ...string) string {
	t.Helper()
	cmd := newPathCmd()
	cmd.SetContext(ctx)
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&bytes.Buffer{})
	cmd.SetArgs(append([]string{"fragment"}, args...))
	if err := cmd.Execute(); err != nil {
		t.Fatalf("fragment %v: %v", args, err)
	}
	return out.String()
}

func seedPathEntries(t *testing.T, ctx context.Context, argv ...[]string) {
	t.Helper()
	for _, args := range argv {
		cmd := newPathCmd()
		cmd.SetContext(ctx)
		cmd.SetOut(&bytes.Buffer{})
		cmd.SetErr(&bytes.Buffer{})
		cmd.SetArgs(args)
		if err := cmd.Execute(); err != nil {
			t.Fatalf("seed %v: %v", args, err)
		}
	}
}

// An rc file with nothing managed is not an error — the fragment is
// just its header.
func TestPathFragment_NoManagedBlocks(t *testing.T) {
	ctx, _, _ := setupEditCmdEnv(t)
	canonical, _ := writeTracked(t, ctx, "export PATH=/usr/bin:$PATH\n")

	got := runPathFragmentCmd(t, ctx, "--file", canonical)
	if !strings.HasPrefix(got, "# Generated by dfm.") {
		t.Fatalf("missing header:\n%s", got)
	}
	if strings.Contains(got, "dfm:path:") {
		t.Errorf("emitted a managed block for an unmanaged rc file:\n%s", got)
	}
}

// --fish swaps the syntax family, not the entries: same dirs, fish body.
func TestPathFragment_FishSelectsOtherFamily(t *testing.T) {
	ctx, _, _ := setupEditCmdEnv(t)
	canonical, _ := writeTracked(t, ctx, "")
	seedPathEntries(t, ctx,
		[]string{"add", "--file", canonical, "/a"},
		[]string{"add", "--file", canonical, "/b"},
		[]string{"add", "--file", canonical, "--append", "/c"},
	)

	posix := runPathFragmentCmd(t, ctx, "--file", canonical)
	fish := runPathFragmentCmd(t, ctx, "--file", canonical, "--fish")

	if !strings.Contains(posix, "for __dfm_d in /a /b; do") {
		t.Errorf("posix fragment missing POSIX loop:\n%s", posix)
	}
	if strings.Contains(posix, "fish_add_path") {
		t.Errorf("posix fragment leaked fish syntax:\n%s", posix)
	}
	if !strings.Contains(fish, "fish_add_path") || strings.Contains(fish, "; do") {
		t.Errorf("fish fragment is not fish syntax:\n%s", fish)
	}
	if !strings.Contains(posix, pathFragmentPosixName) || !strings.Contains(fish, pathFragmentFishName) {
		t.Errorf("headers do not name their own fragment files:\n%s\n%s", posix, fish)
	}
}

// The fragment has to survive its own parser: the blocks it emits carry
// the same ids, dirs and directions the rc file did, prepend first.
func TestPathFragment_RoundTrips(t *testing.T) {
	ctx, _, _ := setupEditCmdEnv(t)
	canonical, _ := writeTracked(t, ctx, "")
	seedPathEntries(t, ctx,
		[]string{"add", "--file", canonical, "/a"},
		[]string{"add", "--file", canonical, "/b"},
		[]string{"add", "--file", canonical, "--append", "/c"},
	)

	got := runPathFragmentCmd(t, ctx, "--file", canonical)
	rows := pathListRows(findPathManagedEntries([]byte(got)))

	want := []pathListRow{
		{Dir: "/a", Direction: pathDirectionPrepend, MarkerID: pathMarkerID(pathDirectionPrepend, []string{"/a", "/b"})},
		{Dir: "/b", Direction: pathDirectionPrepend, MarkerID: pathMarkerID(pathDirectionPrepend, []string{"/a", "/b"})},
		{Dir: "/c", Direction: pathDirectionAppend, MarkerID: pathMarkerID(pathDirectionAppend, []string{"/c"})},
	}
	if len(rows) != len(want) {
		t.Fatalf("got %d rows, want %d:\n%s", len(rows), len(want), got)
	}
	for i, w := range want {
		if rows[i] != w {
			t.Errorf("row %d = %+v, want %+v", i, rows[i], w)
		}
	}

	// Source order, not just set membership: the prepend block's marker
	// must appear before the append block's.
	if strings.Index(got, want[0].MarkerID) > strings.Index(got, want[2].MarkerID) {
		t.Errorf("append block rendered before prepend block:\n%s", got)
	}
}

func TestPathFragment_ShellAndFileMutuallyExclusive(t *testing.T) {
	ctx, _, _ := setupEditCmdEnv(t)
	cmd := newPathCmd()
	cmd.SetContext(ctx)
	cmd.SetOut(&bytes.Buffer{})
	cmd.SetErr(&bytes.Buffer{})
	cmd.SetArgs([]string{"fragment", "--shell", "zsh", "--file", "/tmp/x"})
	err := cmd.Execute()
	if err == nil {
		t.Fatal("want an error when --shell and --file are both set")
	}
	var ee *exitError
	if !errors.As(err, &ee) || ee.code != exitResolveErr {
		t.Fatalf("err = %v, want exit %d", err, exitResolveErr)
	}
	if !strings.Contains(ee.msg, "mutually exclusive") {
		t.Errorf("error message lacks 'mutually exclusive': %q", ee.msg)
	}
}

// A fish rc file yields the fish fragment without --fish, and a zsh one
// yields the POSIX fragment because env.sh is what zsh sources.
func TestPathFragment_FamilyFollowsTarget(t *testing.T) {
	for _, tc := range []struct {
		basename string
		wantFish bool
	}{
		{"config.fish", true},
		{".zshrc", false},
		{".bashrc", false},
	} {
		t.Run(tc.basename, func(t *testing.T) {
			ctx, _, _ := setupEditCmdEnv(t)
			canonical, _ := writeTrackedNamed(t, ctx, tc.basename, "")
			seedPathEntries(t, ctx,
				[]string{"add", "--file", canonical, "/a"},
			)

			got := runPathFragmentCmd(t, ctx, "--file", canonical)
			if isFish := strings.Contains(got, "fish_add_path"); isFish != tc.wantFish {
				t.Errorf("fish fragment = %v, want %v:\n%s", isFish, tc.wantFish, got)
			}
		})
	}
}

// parsePathOpenMarker does not validate direction=, so a hand-edited
// marker can carry anything. dfm path list buckets a non-append
// direction as prepend; the fragment has to render it, not drop it.
func TestPathFragment_UnknownDirectionRendersAsPrepend(t *testing.T) {
	ctx, _, _ := setupEditCmdEnv(t)
	block := wellFormedPathBlock("middle", []string{"/odd"},
		"for __dfm_d in /odd; do : ; done\nunset __dfm_d\nexport PATH\n")
	canonical, _ := writeTracked(t, ctx, block)

	got := runPathFragmentCmd(t, ctx, "--file", canonical)
	if !strings.Contains(got, "/odd") {
		t.Fatalf("entry with direction=middle was dropped:\n%s", got)
	}
	if !strings.Contains(got, `PATH="$__dfm_d${__dfm_new:+:$__dfm_new}"`) {
		t.Errorf("direction=middle did not render as prepend:\n%s", got)
	}
}
